# Generated by Django 4.1.7 on 2023-04-07 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useractivity_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='method',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='path',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
