# Generated by Django 4.1.7 on 2023-04-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useractivity_method_useractivity_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
